### ISSUE TITLE
it throws errors like this.

### ISSUE THREAD

**Issue by hisaotsu** [griffin-stewie/atom-redpen#5]
Validate を押したところ、エラーになってしまいます。Windows 環境なので、サポートされていないのかもしれませんが…。

(1) Windows 環境はサポートされているか
(2) サポートされている場合、何をご提供すれば、バグなのか私の単純な設定ミスかがわかるか

お忙しいところ申し訳ありませんが、教えていただけましたら幸いです。

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package, v0.3.5

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///C:/Users/htsujimu/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Chtsujimu%5C%5CDocuments%5C%5C02_CU%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%2C%7B%22pathToOpen%22%3A%22C%3A%5C%5Credpen%5C%5Cconf%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Chtsujimu%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.19%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Chtsujimu%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.19%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.19%22%2C%22shellLoadTime%22%3A311%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5Chtsujimu%5C%5CDocuments%5C%5C02_CU%22%2C%22C%3A%5C%5Credpen%5C%5Cconf%22%5D%7D:1

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Object.module.exports.parse (C:\Users\htsujimu\.atom\packages\redpen\lib\redpenResultParser.coffee:10:19)
  at C:\Users\htsujimu\.atom\packages\redpen\lib\redpenValidator.coffee:141:25
  at ChildProcess.exithandler (child_process.js:215:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

### Commands

```
     -4:23.2.0 redpen:validate (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:16.9.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
  2x -1:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.6.0 redpen:validate (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "wordpress-api",
      "atom-lint"
    ]
  },
  "redpen": {
    "pathForRedPen": "c:\\redpen\\bin",
    "JAVA_HOME": "C:\\Program Files (x86)\\Java\\jre1.7.0_85;",
    "validateOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
japanese-wrap, v0.2.10
jshint, v1.8.0
jslint, v1.4.0
language-dot, v1.6.0
linkify, v0.11.0
redpen, v0.3.5
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by HaiTo** [comment]
@hisaotsu こちら私も同様の状況になりましたが、設定ファイルの書き方がおかしい可能性があります。
設定ファイル(conf)も貼っていただければ分かるかもしれません。

**Comment by hisaotsu** [comment]
ありがとうございます。
実は、諸処の事情で、環境が変わってしまったので、追跡できなくなってしまいました。お気遣いいただいたのに、すみません。

**Comment by HaiTo** [comment]
:metal:

**Comment by griffin-stewie** [comment]
@hisaotsu さん、問題は解決したのでしょうか？

いただいた質問について

- Q. Windows はサポート対象か？
    - A. 私の方で動作検証環境がありませんのでサポート対象とは言えません。分かる範囲で推測でアドバイス・修正は可能かも知れませんがその点ご了承ください。
- Q. サポートされている場合、何をご提供すれば、バグなのか私の単純な設定ミスかがわかるか
    - A. すでに掲載いただいている内容 + @HaiTo さんのおっしゃるように RedPen 側のバージョンや設定ファイルがあると分かることが増えてくるかと思います。

@HaiTo さん、フォローありがとうございました。
