### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by LincolnHedgehog** [griffin-stewie/atom-redpen#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Unknown Windows Version
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package, v0.3.5

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /C:/Users/masahiro/.atom/packages/redpen/lib/redpenValidator.coffee:77

TypeError: Cannot read property 'getGrammar' of undefined
    at versionCheckHandler (file:///C:/Users/masahiro/.atom/packages/redpen/lib/redpenValidator.coffee:54:18)
    at Validator.module.exports.Validator.redpenVersion (file:///C:/Users/masahiro/.atom/packages/redpen/lib/redpenValidator.coffee:69:9)
    at Validator.module.exports.Validator.needsValidateAsync (file:///C:/Users/masahiro/.atom/packages/redpen/lib/redpenValidator.coffee:61:8)
    at Object.module.exports.Redpen.validate (file:///C:/Users/masahiro/.atom/packages/redpen/lib/redpen.coffee:74:16)
    at atom-workspace.subscriptions.add.atom.commands.add.redpen:validate (file:///C:/Users/masahiro/.atom/packages/redpen/lib/redpen.coffee:40:83)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\masahiro\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\masahiro\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\masahiro\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\masahiro\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\masahiro\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
japanese-menu, v1.7.0
redpen, v0.3.5

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@LincolnHedgehog 
Can you try v0.3.6?
Unfotunatly, I cannot support Windows, because I don't have it.
Thank you.
