### ISSUE TITLE
Uncaught TypeError: path.join is not a function

### ISSUE THREAD

**Issue by Mizuho32** [griffin-stewie/atom-redpen#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package, v0.5.0

### Stack Trace

Uncaught TypeError: path.join is not a function

```
At /home/mizuho/.atom/packages/redpen/lib/redpenValidator.coffee:129

TypeError: path.join is not a function
    at Validator.module.exports.Validator.validate (/home/mizuho/.atom/packages/redpen/lib/redpenValidator.coffee:129:44)
    at /home/mizuho/.atom/packages/redpen/lib/redpen.coffee:79:20
    at versionCheckHandler (/home/mizuho/.atom/packages/redpen/lib/redpenValidator.coffee:63:11)
    at /home/mizuho/.atom/packages/redpen/lib/redpenValidator.coffee:98:11
    at ChildProcess.exithandler (child_process.js:216:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### Commands

```
     -7:11.7.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -7:11.3.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -7:08.6.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -7:03.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false
  },
  "redpen": {
    "JAVA_HOME": "/usr/lib/jvm/java-8-oracle",
    "pathForRedPen": "/home/mizuho/usr/local/redpen/bin/redpen",
    "validateOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
japanese-menu, v1.8.0
keyboard-localization, v1.4.18
redpen, v0.5.0
vim-mode, v0.65.1

# Dev
No dev packages
```

redpenValidator.coffee中の抵当な箇所に`path = require 'path'`を挟んだら動きましたが、一応。

**Comment by yuutaso** [comment]
私も同様の現象で悩んでいます。

>redpenValidator.coffee中の抵当な箇所にpath = require 'path'を挟んだら動きましたが、一応。

こちらの該当場所（行）をお教えいただけませんでしょうか。

**Comment by Mizuho32** [comment]
すでに解決してそうですが176行目です。

**Comment by hujuu** [comment]
redpenをインストールする前にatomにredpenのパッケージインストールしてたら、同じエラーがでました。
一度アンインストールしてから入れ直したら、エラーが出なくなりました。
