### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by yuutaso** [griffin-stewie/atom-redpen#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package 0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.parse (/packages/redpen/lib/redpenResultParser.coffee:10:19)
    at /packages/redpen/lib/redpenValidator.coffee:150:25
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -2:25.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -2:21.6.0 redpen:validate (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
editorconfig 2.2.2 
file-icons 2.1.2 
git-plus 7.3.3 
git-time-machine 1.5.9 
language-markdown 0.20.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
monokai 0.22.0 
node_modules undefined 
project-manager 3.3.4 
redpen 0.5.0 
```

**Comment by sogo-nozaki** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package 0.5.1


### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.parse (/packages/redpen/lib/redpenResultParser.coffee:10:19)
    at /packages/redpen/lib/redpenValidator.coffee:150:25
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  7x -3:59.8.0 core:save (input.hidden-input)
     -2:35.4.0 editor:newline (input.hidden-input)
  2x -2:34.6.0 core:backspace (input.hidden-input)
     -2:22.5.0 core:save (input.hidden-input)
     -2:06.9.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
japanese-menu 1.12.0 
redpen 0.5.1 
```
